name: Python package

on: [push]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.8]
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        tzdata_extras: ["", "tzdata"]
    env:
      TOXENV: py
      TEST_EXTRAS_TOX: ${{ matrix.tzdata_extras }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    steps:
    - uses: actions/checkout@v2
    - name: ${{ matrix.python-version }} - ${{ matrix.os }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip tox
    - name: Run tests
      run: |
        tox
    - name: Report coverage
      run: |
        tox -e coverage-report,codecov

  c_coverage:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.8]
        os: ["ubuntu-latest"]
        compiler: ["gcc-9", "gcc"]
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      CC: ${{ matrix.compiler }}
    steps:
      - uses: actions/checkout@v2
      - name: C coverage - ${{ matrix.os }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt-get -qq update
          sudo apt-get install -y gcc-9
          python -m pip install --upgrade pip tox
      - name: Run tests
        run: |
          tox -e gcov,codecov
      - name: Print diagnostic information
        run: |
          ${{ matrix.compiler }} --version
          strings .tox/gcov/lib/python3.8/site-packages/zoneinfo/*.so | grep gcda
          echo "Find gcda files"
          find . -iname '*.gcda'
          echo "Find gcno files"
          find . -iname '*.gcno'

  other:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        toxenv: ["lint", "build"]
    env:
      TOXENV: ${{ matrix.toxenv }}

    steps:
      - uses: actions/checkout@v2
      - name: ${{ matrix.toxenv }}
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install tox
        run: python -m pip install --upgrade pip tox
      - name: Run action
        run: |
          tox
